import sys
sys.path.insert(0,'C:\\Users\\User\\Desktop\\FYP\\pynaoqi-python2.7-2.5.5.5-win32-vs2013\\lib')
import qi
import argparse
import time
import math
from naoqi import ALProxy


##life_awareness = ALProxy("ALAutonomousLife", "160.69.69.101", 9559)
##life_awareness.setAutonomousAbilityEnabled("BasicAwareness", False)
tts = ALProxy("ALTextToSpeech", "160.69.69.101", 9559)
motion = ALProxy("ALMotion", "160.69.69.101", 9559)
animation= ALProxy("ALAnimationPlayer","160.69.69.101", 9559)
#motion.rest()
motion.wakeUp()
time.sleep(1)
motion.setOrthogonalSecurityDistance(0.05) #These two lines sets the security distances os the robot
motion.setTangentialSecurityDistance(0.04)
animation.run("animations/Stand/Gestures/YouKnowWhat_1")
tts.say("Hello....Welcome to the guided tour")
tts.say("I am Pepper and I will show you my friends around the robotics centre")
tts.say("Follow me")

right = -math.pi/2
left = math.pi/2
reverse = math.pi
motion.moveTo(-0.2,0,0)
motion.moveTo(0,0,3.14159)
##motion.moveTo(0.9,0,0)
##motion.moveTo(0,0,right)
motion.moveTo(1.3,0,0)
motion.moveTo(0,0,right)
tts.say("This is the main corridor")
time.sleep(1)
motion.moveTo(3,0,0)
tts.say("To my left are Jackal and Fetch")
motion.moveTo(0,0,left)
tts.say("Jackal is an autonomous robot for the outdoors")
tts.say("It is a fast four by four car and is waterproof")
tts.say("Jackal is being used to develop pedestrian detection algorithms")
time.sleep(0.5)
tts.say("The big white robot is Fetch")
tts.say("Fetch has 7 degrees of freedom")
tts.say("He can pick up all sorts of things with his gripper")
tts.say("He gets used for a lot of research")
tts.say("He is used to pick up balls and small objects upto 6 kilograms")
tts.say("He is a favourite in every lab for research in automation")
motion.moveTo(0,0,right)
motion.post.moveTo(4,0,0)
tts.say("This is where I sleep after a hard days work ")
motion.moveTo(4,0,0)
motion.moveTo(0,0,right)
##motion.moveTo(4.4,0,0)
##motion.moveTo(0,0,right)
##motion.moveTo(5,0,0)
##motion.moveTo(0,0,left)
##motion.moveTo(2,0,0)
#tts.say("This is Panda")
##motion.moveTo(0,0,reverse)
##motion.moveTo(2,0,0)
##motion.moveTo(0,0,right)
##motion.moveTo(13.5,0,0)
##motion.moveTo(0,0,right)
##motion.moveTo(1,0,0)
##tts.say("This is Baxter")
##motion.moveTo(0,0,reverse)
##motion.moveTo(1,0,0)
##motion.moveTo(0,0,right)
##motion.moveTo(12.3,0,0)
##motion.moveTo(0,0,left)
##motion.moveTo(4.5,0,0)
##motion.moveTo(0,0,right)
##motion.moveTo(2,0,0)
##motion.moveTo(0,0,right)
##tts.say("This is Panda 2")
##motion.moveTo(0,0,right)
##motion.moveTo(49,0,0)
##tts.say("The tour is over")
##tts.say("Thank you for coming")
##
