import time
from naoqi import ALProxy
tts = ALProxy("ALTextToSpeech", "160.69.69.101", 9559)
#tts.say("Hello, world!")
tts.say("Welcome to the guided tour")
tts.say("This is Monash")
time.sleep(2)
#tts.say("This is the Baxter robot")
Navigation = ALProxy("ALNavigation", "160.69.69.101", 9559)
motion = ALProxy("ALMotion", "160.69.69.101", 9559)
#motion.setStiffnesses("Body", 1.0)
##tts.say("Jackal is an autonomous robot for the outdoors")
##tts.say("It is a fast four by four car and is waterproof")
##time.sleep(2)
##tts.say("The big blue guy is Fetch")
##tts.say("Fetch has 7 degrees of freedom")
##tts.say("He can pick up all sorts of things with his gripper")
##tts.say("He gets used for a lot of research")
##
motion.wakeUp()
motion.moveTo(1,0,0)
##motion.moveTo(0,0,0)
#motion.moveTo(0,0,1.57)
#motion.moveInit()
#motion.post.moveTo(1, 0, 0)
#tts.say("I'm walking")
